app.name='Centralized Configuration'
# leave a comment here, just know i was here at Oct fourth 23:00 😪✌️
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
