server.port=0

# PostgreSQL DB Config
spring.datasource.url=jdbc:postgresql://localhost:5000/ice-skate-db
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=pricing_schema

# Flyway Migrations
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=pricing_schema
spring.flyway.default-schema=pricing_schema
spring.flyway.table=flyway_schema_history

